### PR TITLE
Format deleted & inserted line with before selector

### PR DESCRIPTION
**Pull request by olimart**
When copy/paste entire files/sections, both `-` & `+` symbols are part of the selection.

By using `::before` selector to mark corresponding lines, symbols are not part of the selection, therefore no need to remove those in your editor after copy-paste.

However, I'm not sure where `-` & `+` symbols are coming from so I guess they should be removed from the initial markup.

Fix inconsistent indentation as well.

### CODE REVIEW

**Comment by xymbol** [comment]
This is great, just jumped in to see if this had already been submitted.

@olimart Need help getting the +/- chars removed?

**Comment by olimart** [comment]
@xymbol indeed, help appreciated to remove the +/- chars

**Comment by xymbol** [comment]
@olimart The build seems to be broken. Looking into that.

**Comment by xymbol** [comment]
@olimart Picked your commit, fixed the build and changed how lines are rendered. Feel free to push on top of your pull-request. https://github.com/xymbol/railsdiff/commits/improve-copypasta

**Comment by olimart** [comment]
@xymbol do you know how to fetch your commits with git since we work on separate repo?

**Comment by xymbol** [comment]
Sure, should be something like:

```shell
# fetch commits into your branch
git checkout patch-1
git remote add xymbol https://github.com/xymbol/railsdiff.git
git fetch --all
git reset --hard xymbol/improve-copypasta

# make sure things work look good
npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install
ember test
ember serve

# then, update your pull-request
git push -f
```

Look forward to see it online!

**Comment by olimart** [comment]
Thanks @xymbol 

@jswanner @nbibler Can you take a look?

**Comment by xymbol** [comment]
@olimart We don't need that many commits, should be 4 in total. If you provide me with access, I can squash them for you.

**Comment by jswanner** [comment]
I'm sorry I hadn't noticed this PR/discussion before now, and thanks @olimart & @xymbol for wanting to contribute to the project.

I'm currently debating with myself how I feel about this change. To me, when viewing the changes of generated apps between 2 different Rails versions, I feel like I'm looking at a diff/patch file with some color-coding and line numbers added. Therefore, the coloring & the line numbers are extraneous from the diff and shouldn't be selectable/copied (as is the case), but the first character of each line of a diff is significant.

I'm trying to understand your use-case. I'm assuming you are:

1. Selecting the whole diff for a file
1. Pasting that into your text editor
1. Removing all the lines that were deleted
1. Removing the first character from each remaining line

Your request is to change what gets copied so that you can skip the fourth step. Except, there's another problem: what you paste into your editor will not contain the information you need to do the third step.

What I would say is the problem is that you cannot copy a properly formatted diff file, so that you can use `git apply` or `patch`. For instance, you can get to the raw diff file from the API that RailsDiff uses, and then apply those patches. Such as: `curl "http://api.railsdiff.org/v5.0.2/v5.1.1" | git apply -p2 --reject -` or `curl "http://api.railsdiff.org/v5.0.2/v5.1.1" | patch -p2`.

So, how I'm feeling right now: I would definitely be open to a change that provides an easy way to copy a properly formatted diff into someone's clipboard, but I don't think this change really improves a user's experience.

But, perhaps I'm mistaken about your use-case and how this change would help you.

**Comment by xymbol** [comment]
@jswanner I like both use cases and, would probably support both. Many times I find myself in the situation where I can't/don't want to apply a full patch but, the important bits and pieces.

On a side note, some commits fix the build and restore a test that was left out. It's all green on Travis CI now. https://travis-ci.org/xymbol/railsdiff/builds/242109355

**Comment by olimart** [comment]
@xymbol GH has the option to squash automatically commits when merging.

@jswanner my personal experience is Rails adds more than delete stuff.
So, I end up copy/paste not the entire file but just the applicable changes, then remove manually symbols.

I agree if you copy/paste the entire file, then it may be difficult to read correctly the changes since all symbols are gone.

**Comment by jswanner** [comment]
I know it's a little different, but I feel like #9 is a better solution to your use-case than this PR.

**Comment by olimart** [comment]
Closing since @jswanner wants to go with #9 instead. Thanks @xymbol for the help.

**Pull request closed without merging**
